version: '3'

services:
  order-service:
    image: order:dev
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command:
      "CompileDaemon -build='make build' -command='./bin/order' --graceful-kill"
    env_file: .env

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    env_file: .env

