steps:
  - label: ":information_source: Print info"
    command: "./.buildkite/scripts/info.sh"
  - label: ":golang: Running linters."
    command: "./scripts/lint.sh"
  - block: ":golang: test"
  - label: ":golang: Running unit tests."
    command: "./scripts/test.sh 'unit'"
  - label: ":golang: Running integration tests."
    command: "./scripts/test.sh 'integration'"

